[project]
name = "bib2yaml"
version = "0.1.0"
description = "Library and CLI to convert BibTeX bibliography file to YAML file"
readme = "README.md"
authors = [
    { name = " Sahil Jhawar"}
]
requires-python = ">=3.12"
dependencies = [
    "bibtexparser>=1.4.3",
    "pylatexenc>=2.10",
    "pyyaml>=6.0.3",
]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
bib2yaml = "bib2yaml.bib2yaml:main"
